### ISSUE TITLE
files in /res/raw are zero-sized.

### ISSUE THREAD

**Issue by alex9yust** [Evolution-X-AOSP/packages_apps_Settings#234]
face_education.mp4 
face_education_lottie.json 
face_enroll_introduction_animation.mp4 
face_settings.mp4 
fingerprint_edu_lottie.json 
fingerprint_edu_lottie_portrait.json 
face_education.mp4

**Comment by alex9yust** [comment]
fingerprint_edu_lottie.json
fingerprint_edu_lottie_portrait.json

these files are needed to add a fingerprint.
https://github.com/Evolution-X/frameworks_base/issues/367#issue-1500755096

**Comment by joeyhuab** [comment]
> fingerprint_edu_lottie.json fingerprint_edu_lottie_portrait.json
> 
> these files are needed to add a fingerprint. [Evolution-X/frameworks_base#367 (comment)](https://github.com/Evolution-X/frameworks_base/issues/367#issue-1500755096)

Fixed with rebase of https://github.com/Evolution-X/packages_apps_Settings/commit/63c4b10f03750eb90913f7f3bc0d97f84e438974.

Others aren't necessary.
