### ISSUE TITLE
do not translate build_maintainer_summary

### ISSUE THREAD

**Issue by alex9yust** [Evolution-X-AOSP/packages_apps_Settings#69]
https://github.com/Evolution-X/packages_apps_Settings/blob/defc5499113a722ab2c1a45024184b4774cdf8d7/res/values-ja-rJP/evolution_strings.xml#L27 and
nl-rNL
pt-rBR
ru-rRU
tr-rTR
zh-rTW

**Comment by joeyhuab** [comment]
Fixed with https://github.com/Evolution-X/packages_apps_Settings/commit/2006333431cbc0604d1e83ae3bba15b323261565.

Thanks!
